config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'
      }
  devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  resources :users
  resources :admins
  resources :rewards
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/:id/' => 'users#refresh', via: [:patch], :as => :refresh
  put '/users/addToRoster' => 'users#add_user_to_roster'
  

end

app/views/admins/show.html.erb
<body style="background-color: #49dda5;">
	<br>
	<div class="container-fluid">
			<div class="hidden-xs hidden-sm col-md-3 col-lg-3">
				<div class="panel panel-default fixed-top">
					<div class="panel-body">
						<center>
							<% if current_admin.avatar_file_name != nil %>
								<%= image_tag current_admin.avatar.url(:medium), class: "img img-responsive img-thumbnail img-rounded", size: "240"%>
							<% else %>
								<img src="http://www.faithlineprotestants.org/wp-content/uploads/2010/12/facebook-default-no-profile-pic.jpg" height="175" width="175" class="img img-responsive img-thumbnail img-rounded">
							<% end %>
						</center>
						<br>
						<a class="btn btn-default btn-block" href="/"><i class="fa fa-home"></i> Home</a>
						<a class="btn btn-default btn-block" href="<%= users_path %>"><i class="glyphicon glyphicon-user"></i> Clients</a>
						<a class="btn btn-default btn-block" href="/rewards"><i class="fa fa-check"></i> Bonuses</a>
					</div>	
				</div>
			</div>
			<div class="hidden-md hidden-lg col-xs-1 col-sm-1"></div>
			<div class="col-xs-8 col-sm-8 col-md-9 col-lg-9">
			<% if @users.each != nil %>
				<div class="panel panel-default">
					<div class="panel-body">
						<!-- <form class="form" role="search">
						<div class="col-sm-11">	
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Search for Client...">
							</div>
						</div>
						<button class="btn btn-primary"><i class="fa fa-search"></i></button>
						</form> -->
						<table class="table"> 
							<% @users.each do |user| %>
										<tr>
												<td>
													<div class="row">
													<div class="col-xs-10 col-sm-10 col-md-4 col-lg-4 text-center">
														<%= link_to user_path(user), class: "btn" do %>
															<% if user.avatar_file_name %>
                												<%= image_tag user.avatar.url(:medium), class: "img img-responsive img-thumbnail img-rounded", size: "175"%>
															<% elsif user.image %>
																<%= image_tag user.image, size: "175", class: "img img-responsive img-thumbnail img-rounded" %>
															<% elsif user.fitbit_image %>	
																<%= image_tag user.fitbit_image, class: "img img-responsive img-thumbnail img-rounded", size: "175" %>
															<% else %>
																<img src="http://www.faithlineprotestants.org/wp-content/uploads/2010/12/facebook-default-no-profile-pic.jpg" height="175" width="175" class="img img-responsive img-thumbnail img-rounded">
															<% end %>	
														<% end %>
													</div>
													<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8"><h1 class="text-muted"><a class="text-muted"href="<%= user_path(user) %>"><%= user.fname %></a></h1>
													<p><%= truncate(user.about, length: 600, omission: " [...]") %></p>
														<a type="button" href="<%= user_path(user) %>" class="btn btn-default"><i class="fa fa-eye"></i> View</a>
											               <!-- <%= bootstrap_form_for user, layout: :horizontal do |f| %>
											                  <%= f.text_field :admin_id, value: "nil", class: "hidden", hide_label: true  %>
											                  <%= f.submit "Remove From Roster", class: "btn btn-danger" %>
											                <% end %>-->
													</div>
													</div>
												</td>
										</tr>
							<% end %>
						</table>
						<center><%= will_paginate @users, renderer: BootstrapPagination::Rails %></center>
					</div>
				</div>
			<% end %>
			</div>
	</div>
</body>