config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'
      }
  devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  resources :users
  resources :admins
  resources :rewards
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/:id/' => 'users#refresh', via: [:patch], :as => :refresh
  put '/users/addToRoster' => 'users#add_user_to_roster'
  

end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :admin
	validates_presence_of :title
	validates_presence_of :target_unit
	validates_presence_of :goal
	validates_presence_of :period
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
	before_action :authenticate_admin!, :except => [:index, :show]
	layout 'application'
	def new
		@reward = Reward.new
	end
	
	def create
		@reward = Reward.new(reward_params)
		@reward.admin_id = current_admin.id
		@reward.company = current_admin.insurance_provider
		if @reward.save
			@reward.save
			redirect_to @reward
		else
			render 'new'
		end
	end
	
	def show
		@reward = Reward.find(params[:id])
	end
	
	def index
  		@rewards = Reward.paginate(:page => params[:page], :per_page => 4)
  		@rewards = @rewards.reverse_order
  		@admins = Admin.paginate(:page => params[:page], :per_page => 2)
  		@admins = @admins.reverse_order
	end
	
	def edit
		if current_admin.id == Reward.find(params[:id]).admin_id
			@reward = Reward.find(params[:id])
		else
			flash[:alert] = "Whoops! You can only edit bonuses you created."
		end
	end
	
	def update
		@reward = Reward.find(params[:id])
		
		if @reward.update(reward_params)
			redirect_to @reward
		else
			render 'edit'
		end
	end
	
	def destroy
		if current_admin.id == Reward.find(params[:id]).admin_id
			@reward = Reward.find(params[:id])
			@reward.destroy
			redirect_to rewards_path
		else
			flash[:alert] = "Whoops! You can only delete bonuses you created."
			redirect_to current_admin
		end
	end
		      
	private
		def reward_params
			params.require(:reward).permit(:title, :description, :reward, :target_unit, :goal, :period)
		end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= bootstrap_form_for @reward do |f| %>
  
  <% if @reward.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@reward.errors.count, "error") %> prohibited
    this reward from being created:</h2>
  
    <ul>
    <% @reward.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="panel">
    <div class="panel-body">
      <p>
        <%= f.text_field :title %>
        <%= f.text_area :description %>
        <%= f.number_field :reward %>
        <%= f.select :target_unit, ["Calories", "Steps", "Miles"], label: "Category" %>
        <%= f.number_field :goal, label: "Target Goal" %>
        <%= f.select :period, ["24-Hours", "Month"], label: "Period" %>
        <%= f.text_field :company, hide_label: true, class: "hidden hidden-lg hidden-md hidden-sm hidden-xs" %>
        <%= f.submit "Create", class: "btn btn-success btn-block"%>
      </p>
    </div>
  </div>
<% end %>  

app/views/rewards/_update_form.html.erb
<%= bootstrap_form_for @reward do |f| %>
  
  <% if @reward.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@reward.errors.count, "error") %> prohibited
    this reward from being created:</h2>
  
    <ul>
    <% @reward.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="panel">
    <div class="panel-body">
      <p>
        <%= f.text_field :title %>
        <%= f.text_area :description %>
        <%= f.number_field :reward %>
        <%= f.select :target_unit, ["Calories", "Steps", "Miles"], label: "Category" %>
        <%= f.select :goal, [2500,5000,10000,20000,40000,60000], label: "Target Goal" %>
        <%= f.select :period, ["24-Hours", "Month"], label: "Period" %>
        <%= f.text_field :company, hide_label: true, class: "hidden" %>
        <%= f.submit "Update", class: "btn btn-default btn-block"%>
      </p>
    </div>
  </div>
<% end %>  

app/views/rewards/edit.html.erb
<html>
  <head>
  	<title><%= @reward.title %></title>
  </head>
  <body>
      <div class="container">
      <br>
        <div class="row">
	  
        <!-- Edit Form -->
	    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
          <div class="panel panel-default">
	          <div class="panel-heading"><h4><i class="fa fa-edit fa-1x"> Edit Bonus</h4></i></div>
	          <div class="panel-body"> 
		      	<%= render 'update_form' %>
		      </div>
	      </div>
    	</div>
	    
	    <!-- Sidebar -->
	    <div class="container-fluid">
	      <div class="row">
	      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
		      <div class="panel panel-default">
	          	<div class="panel-heading">
	          		<h4>
	          			<i class="fa fa-edit fa-1x"></i> 
	          			Delete Bonus
	          		</h4>
          		</div>
		        <div class="panel-body">
					<%= link_to 'Delete', reward_path(@reward), :class => "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
		      </div>
	    </div>
	    </div>
        </div>
      </div>
  	</h4>
  </body>
</html>

app/views/rewards/index.html.erb
<html>
	<head>
		  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag :defaults %>
		  <%= csrf_meta_tags %>
		  <link href="/assets/stylesheets/css/yeti2-bootstrap.css" rel="stylesheet">
		  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
		<title>FitHub | Bonuses</title>
	</head>
	<body>
		<div class="container">
		<br>
			<div class="container">
			<div class="well well-lg">
				<h1 class="text-center">Available Bonuses 
				<% if admin_signed_in? %>
					<a href="/rewards/new" class="btn btn-default btn-lg"><i class="fa fa-plus" style="padding-right: 5px;"></i> Add New Bonus</a>
				<% end %>
				</h1>

					<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<br>
						<br>
						
							<% @rewards.each do |reward| %>
								<div class="col-md-6 col-lg-4">
									<% if reward.target_unit == "Calories" %>
										<div class="panel panel-warning">
									<% elsif reward.target_unit == "Steps" %>
										<div class="panel panel-success">
									<% else %>
										<div class="panel panel-danger">
									<% end %>
									
									<div class="panel-heading text-center" style="color: #000000">
									<h3 style="color: #F7F7F7;">
										<% if reward.target_unit == "Calories" %>
											<i class="glyphicon glyphicon-fire"></i>
										<% elsif reward.target_unit == "Steps" %>
											<i class="fa fa-heartbeat"></i>
										<% else %>
											<i class="fa fa-bicycle"></i>
										<% end %>
										<%= reward.title %>
									</h3>
									</div>
										<div class="panel-body">							
											<center>
												<h4 style="color: #000000; text-decoration: none;">Units: <%= reward.target_unit %></h4>
												<h4 style="color: #000000; text-decoration: none;">Goal: <%= number_with_delimiter(reward.goal, :delimeter => ',') %> <%= reward.target_unit %></h4>
												<h4 style="color: #000000; text-decoration: none;">Period: <%= reward.period %></h4>
											</center>
											<br>
											<%= link_to "View Bonus", reward_path(reward), class: "btn btn-default btn-block" %>
										</div>
									</div>
								</div>
							<% end %>
						</div>
					</div>
				<%= will_paginate @rewards, renderer: BootstrapPagination::Rails %>
			</div>
			</div>	
		</div>
	</body>
</html>

app/views/rewards/new.html.erb
<html>    
    <body>
      <div class="container">
      <br>
        <div class="row"> 
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading"><h3><i class="fa fa-edit"></i> Add Bonus</h3></div>
              <div class="panel-body">
              <%= render 'form' %>
              </div>
            </div>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/rewards/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @reward.title %></title>
  </head>
  <body>
    <div class="container-fluid">
    <br>
      <div class="col-lg-12" style="padding-bottom: 20px;">
        <div class="well">
          <div class="row">
              <div class="col-lg-10 col-lg-offset-1">
                <div class="text-center text-capitalize">
                	<h1><%= @reward.title %>
                  <br>
                    <% if Admin.find(@reward.admin_id).fname != nil %>
                      <small>Created by: <%= @reward.company %> (<%= Admin.find(@reward.admin_id).fname %> <%= Admin.find(@reward.admin_id).lname %>)</small>
                  </h1>
                    <% if admin_signed_in? %>
                      <% if current_admin.id == @reward.admin_id %>
                        <div class="btn-group">
                          <a type="button" class="btn btn-default btn-sm" href="<%= edit_reward_path %>">Edit</a> 
                          <%= link_to 'Delete', reward_path(@reward), :class => "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                        </div>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
                <br>
              </div>
          </div>
          <div class="row">
              <div class="col-lg-10 col-lg-offset-1">
                <br>
                <p class="lead">
                  Description: <%= @reward.description %>
                </p>
              	<p class="lead">
                  Reward: $<%= @reward.reward %>.00<br>
              	  Category: <%= @reward.target_unit %><br>
                  Goal: <%= number_with_delimiter(@reward.goal, :delimeter => ',') %><br>
                  Period: <%= @reward.period %><br>
              	</p>
              </div>
          </div>
        </div>
        <a href="/rewards" class="btn btn-default btn-block">View All Bonuses</a>
      </div>
    </div>
  </body>
</html>