config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'
      }
  devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  resources :users
  resources :admins
  resources :rewards
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/:id/' => 'users#refresh', via: [:patch], :as => :refresh
  put '/users/addToRoster' => 'users#add_user_to_roster'
  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="/app/assets/stylesheets/lumen.bootstrap.css" rel="stylesheet">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/special-page.css">
  <link rel="icon" type="image/png" href="http://i.imgur.com/KTY2RnU.png">
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse">
	    <div class="navbar-header" style="padding-top: 8px; padding-bottom: 30px;">
	      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-inverse-collapse">
	        <span class="fa fa-navicon fa-2x"></span>
	      </button>
	        <%= link_to root_path, class: "navbar-brand" do %>
	          <% image_tag("https://s3-us-west-1.amazonaws.com/fithub-development/fithub_logo_2.png", height: '50', width: '100') %>
	        <% end %>
	    </div>
	    <div class="navbar-collapse collapse" id="navbar-inverse-collapse">

	      <ul class="nav navbar-nav navbar-right" style="padding-top: 10px;">
          	<% if admin_signed_in? %>
	          <li>
	            <%= link_to current_admin do %>
	          		<% if current_admin.avatar_file_name != nil %>
	                  <%= image_tag current_admin.avatar.url(:thumb), size: "40", class: " img img-circle" %>
	                <% else %>
	                  <img src="https://s3-us-west-1.amazonaws.com/fithub-development/no-user-image-square.jpg" alt="No Avatar Exists" class="img img-rounded" width="32" height="32">
	                <% end %>
	                <%= current_admin.fname %>
	          	<% end %>
	          </li>
	        
	          <li class="dropdown hidden-xs">
	            <a href="#" class="dropdown-toggle btn btn-lg" type="button" id="dropdownMenu2" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-cog fa-3x"></span></a>
	            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
	              <li role="presentation" class="dropdown-header">Profile</li>
	              <li role="presentation"><%= link_to edit_admin_registration_path do %><i class="fa fa-edit"></i> Edit<% end %></li>
	              <li class="divider"></li>
	              <li role="presentation" class="dropdown-header">Bonus</li>
              	  <li role="presentation"><%= link_to new_reward_path do %><i class="fa fa-plus"></i> Add Bonus<% end %></li>
              	  <li role="presentation"><%= link_to rewards_path do %><i class="fa fa-edit"></i> Edit Bonuses<% end %></li>
              	  <li role="presentation"><%= link_to rewards_path do %><i class="fa fa-check"></i> View Bonuses<% end %></li>
              	  <li class="divider"></li>
              	  <li role="presentation"><%= link_to destroy_admin_session_path, method: :delete do %><i class="fa fa-lock"></i> Sign Out<% end %></li>
	            </ul>
	          </li>
	        <% else %>
	          <li>
	            <%= link_to new_admin_session_path do %>
	              <i class="fa fa-sign-in"></i> Log In
	            <% end %>   
	          </li>
	          <li>
	            <%= link_to new_admin_registration_path do %>
	                  <i class="fa fa-check"></i> Sign Up
	              <% end %>
	          </li>
	        <% end %>
	      </ul>
	    </div>
  	</div>
	<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="/app/assets/stylesheets/lumen.bootstrap.css" rel="stylesheet">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/basic-page.css">
  <link rel="icon" type="image/png" href="http://i.imgur.com/KTY2RnU.png">
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="navbar-header" style="padding-top: 5px; padding-bottom: 25px;">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-inverse-collapse">
        <span class="fa fa-navicon fa-2x"></span>
      </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <% image_tag("https://s3-us-west-1.amazonaws.com/fithub-development/fithub_logo_2.png", height: '50', width: '100') %>
          <% end %>
    </div>
    <div class="navbar-collapse collapse" id="navbar-inverse-collapse">

      <ul class="nav navbar-nav navbar-right" <% if user_signed_in? || admin_signed_in? %>style="padding-top: 5px;" <% else %> style="padding-top: 15px;"<% end %>>
        <% if user_signed_in? != true %>
          <% if admin_signed_in? != true %>
            <li>
              <%= link_to new_user_session_path do %>
                <i class="fa fa-sign-in"></i> Log In
              <% end %>   
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                    <i class="fa fa-check"></i> Sign Up
                <% end %>
            </li>
          <% end %>
        <% else %>
          <li>
            <%= link_to current_user do %>
              <% if current_user.avatar_file_name %>
                  <%= image_tag current_user.avatar.url(:thumb), size: "40", class: "img img-circle" %>
              <% elsif current_user.image %>
                  <%= image_tag current_user.image, size: "40", class: "img img-circle" %>
                <% elsif current_user.fitbit_image != nil %>
                  <%= image_tag current_user.fitbit_image, size: "40", class: " img-circle" %>
                <% else %>
                  <img src="https://s3-us-west-1.amazonaws.com/fithub-development/no-user-image-square.jpg" alt="No Avatar Exists" class="img img-rounded" width="32" height="32">
                <% end %>
              <% end %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle btn btn-lg" type="button" id="dropdownMenu2" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-cog fa-3x"></span></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
              <li role="presentation" class="dropdown-header">Profile</li>
              <li role="presentation"><%= link_to edit_user_registration_path do %><i class="fa fa-edit"></i> Edit<% end %></li>  
              <li class="divider"></li>
              <li role="presentation" class="dropdown-header">Bonus</li>
              <li role="presentation"><%= link_to rewards_path do %><i class="fa fa-check"></i> View Bonuses<% end %></li>
              <li class="divider"></li>
              <li role="presentation"><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-lock"></i> Sign Out<% end %></li>
            </ul>
          </li>
        <% end %>
        <% if admin_signed_in? %>
            <li>
              <%= link_to current_admin do %>
                <% if current_admin.avatar_file_name != nil %>
                    <%= image_tag current_admin.avatar.url(:thumb), size: "40", class: " img img-circle" %>
                  <% else %>
                    <img src="https://s3-us-west-1.amazonaws.com/fithub-development/no-user-image-square.jpg" alt="No Avatar Exists" class="img img-rounded" width="32" height="32">
                  <% end %>
                  <%= current_admin.fname %>
              <% end %>
            </li>
          
            <li class="dropdown hidden-xs">
              <a href="#" class="dropdown-toggle btn btn-lg" type="button" id="dropdownMenu2" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-cog fa-3x"></span></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                <li role="presentation" class="dropdown-header">Profile</li>
                <li role="presentation"><%= link_to edit_admin_registration_path do %><i class="fa fa-edit"></i> Edit<% end %></li>
                <li role="presentation"><%= link_to destroy_admin_session_path, method: :delete do %><i class="fa fa-lock"></i> Sign Out<% end %></li>
                <li class="divider"></li>
                <li role="presentation" class="dropdown-header">Bonus</li>
                <li role="presentation"><%= link_to new_reward_path do %><i class="fa fa-plus"></i> Add Bonus<% end %></li>
                <li role="presentation"><%= link_to rewards_path do %><i class="fa fa-edit"></i> Edit Bonuses<% end %></li>
                <li role="presentation"><%= link_to rewards_path do %><i class="fa fa-check"></i> View Bonuses<% end %></li>
              </ul>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
	<%= yield %>
    <!-- Smooth Scroll -->
    <script type="text/javascript">
      (function (jQuery) {
        jQuery.mark = {
          jump: function (options) {
            var defaults = {
              selector: 'a.smooth-scroll'
            };
            if (typeof options == 'string') defaults.selector = options;
            var options = jQuery.extend(defaults, options);
            return jQuery(options.selector).click(function (e) {
              var jumpobj = jQuery(this);
              var target = jumpobj.attr('href');
              var thespeed = 1000;
              var offset = jQuery(target).offset().top;
              jQuery('html,body').animate({
                scrollTop: offset
              }, thespeed, 'swing')
              e.preventDefault();
            })
          }
        }
      })(jQuery);


      jQuery(function(){  
        jQuery.mark.jump();
      });
  </script><!-- Smooth Scroll -->
</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="/app/assets/stylesheets/lumen.bootstrap.css" rel="stylesheet">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/special-page.css">
  <link rel="icon" type="image/png" href="http://i.imgur.com/KTY2RnU.png">
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse" style="padding-top: 0px;">
	    <div class="navbar-header" style="padding-top: 8px; padding-bottom: 30px;">
	      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-inverse-collapse">
	        <span class="fa fa-navicon fa-2x"></span>
	      </button>
	        <%= link_to root_path, class: "navbar-brand" do %>
	          <% image_tag("https://s3-us-west-1.amazonaws.com/fithub-development/fithub_logo_2.png", height: '49.7', width: '100') %>
	        <% end %>
	    </div>
	    <div class="navbar-collapse collapse" id="navbar-inverse-collapse">

	      <ul class="nav navbar-nav navbar-right" style="padding-top: 10px;">
	        <% if user_signed_in? != true %>
	        	<% if admin_signed_in? != true %>
		          <li>
		            <%= link_to new_user_session_path do %>
		              <i class="fa fa-sign-in"></i> Log In
		            <% end %>   
		          </li>
		          <li>
		            <%= link_to new_user_registration_path do %>
		                  <i class="fa fa-check"></i> Sign Up
		              <% end %>
		          </li>
	          	<% end %>
	        <% else %>
	          <li>
	            <%= link_to current_user do %>
              		<% if current_user.avatar_file_name %>
                		<%= image_tag current_user.avatar.url(:thumb), size: "40", class: " img img-circle" %>
              		<% elsif current_user.image %>
	                  	<%= image_tag current_user.image, size: "40", class: " img-circle", style: "padding-right: 1px;" %>
	                <% elsif current_user.fitbit_image %>
	                  <%= image_tag current_user.fitbit_image, size: "40", class: " img img-circle" %>
	                <% else %>
	                  <img src="https://s3-us-west-1.amazonaws.com/fithub-development/no-user-image-square.jpg" alt="No Avatar Exists" class="img img-rounded" width="32" height="32">
	                <% end %>
	                <h5 class="text-capitalize text-muted" style="display: inline;"> <%= current_user.fname %> </h5>
	              <% end %>
	          </li>
	        <% end %>
	        <% if user_signed_in? %>
	          <li class="dropdown hidden-xs">
	            <a href="" class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-cog fa-3x"></span></a>
	            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
	              <li role="presentation" class="dropdown-header">Profile</li>
	              <li role="presentation"><%= link_to edit_user_registration_path do %><i class="fa fa-edit"></i> Edit<% end %></li>
	              <li class="divider"></li>
	              <li role="presentation" class="dropdown-header">Bonus</li>
          		  <li role="presentation"><%= link_to rewards_path do %><i class="fa fa-check"></i> View Bonuses<% end %></li>
          		  <li class="divider"></li>
          		  <li role="presentation"><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-lock"></i> Sign Out<% end %></li>
	            </ul>
	          </li>
	        <% end %>
    	    <% if admin_signed_in? %>
	          <li>
	            <%= link_to current_admin do %>
	          		<% if current_admin.avatar_file_name != nil %>
	                  <%= image_tag current_admin.avatar.url(:thumb), size: "40", class: " img img-circle" %>
	                <% else %>
	                  <img src="https://s3-us-west-1.amazonaws.com/fithub-development/no-user-image-square.jpg" alt="No Avatar Exists" class="img img-rounded" width="32" height="32">
	                <% end %>
	                <%= current_admin.fname %>
	          	<% end %>
	          </li>
	        
	          <li class="dropdown hidden-xs">
	            <a href="#" class="dropdown-toggle btn btn-lg" type="button" id="dropdownMenu2" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-cog fa-3x"></span></a>
	            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
	              <li role="presentation" class="dropdown-header">Profile</li>
	              <li role="presentation"><%= link_to edit_admin_registration_path do %><i class="fa fa-edit"></i> Edit<% end %></li>
	              <li role="presentation"><%= link_to destroy_admin_session_path, method: :delete do %><i class="fa fa-lock"></i> Sign Out<% end %></li>
	            </ul>
	          </li>
	        <% end %>
	      </ul>
	    </div>
	  </div>
  	</div>
	<%= yield %>
</body>
</html>